export const recipes = [
  {
    id: "1",
    name: "Paneer Tikka Masala",
    category: "Other",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761838933/recipe-reveal/recipes-images/paneer-tikka-16-4_telfkg.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761838930/recipe-reveal/recipes-images/paneer-tikka-1-1_gaikpp.png',
    rating: 4.8,
    reviews: 234,
    prepTime: "20min",
    cookTime: "30min",
    calories: 420,
    protein: 18,
    description:
      "A rich and creamy North Indian curry made with marinated paneer cubes cooked in a spiced tomato-based gravy. Perfect for dinner with naan or rice.",
    ingredients: [
      {
        name: "Paneer",
        quantity: "400g",
        priceRange: "₹80-120",
        estimatedPrice: 100,
      },
      {
        name: "Tomatoes",
        quantity: "4 medium",
        priceRange: "₹20-30",
        estimatedPrice: 25,
      },
      {
        name: "Onions",
        quantity: "2 large",
        priceRange: "₹15-25",
        estimatedPrice: 20,
      },
      {
        name: "Cashews",
        quantity: "1/4 cup",
        priceRange: "₹40-60",
        estimatedPrice: 50,
      },
      {
        name: "Cream",
        quantity: "1/2 cup",
        priceRange: "₹30-50",
        estimatedPrice: 40,
      },
      {
        name: "Garam Masala",
        quantity: "2 tsp",
        priceRange: "₹5-10",
        estimatedPrice: 8,
      },
      {
        name: "Kashmiri Red Chili",
        quantity: "1 tbsp",
        priceRange: "₹5-10",
        estimatedPrice: 7,
      },
      {
        name: "Ginger-Garlic Paste",
        quantity: "2 tbsp",
        priceRange: "₹10-15",
        estimatedPrice: 12,
      },
    ],
    preCookingProcess: [
      "Cut paneer into 1-inch cubes and soak in warm salted water for 10 minutes",
      "Marinate paneer with yogurt, kashmiri chili, and garam masala for 15 minutes",
      "Soak cashews in warm water for 15 minutes",
      "Roughly chop tomatoes and onions",
    ],
    cookingProcess: [
      "Heat oil in a pan and shallow fry marinated paneer until golden. Set aside",
      "In the same pan, add butter and sauté chopped onions until golden brown",
      "Add ginger-garlic paste and cook for 1 minute until raw smell disappears",
      "Add chopped tomatoes and cook until they turn mushy (about 8-10 minutes)",
      "Add cashew paste, salt, and all spices. Cook for 2-3 minutes",
      "Add water to adjust consistency and bring to a boil",
      "Add fried paneer cubes and simmer for 5 minutes",
      "Finish with cream and kasuri methi (dried fenugreek leaves)",
    ],
    postCookingProcess: [
      "Garnish with fresh cream and chopped coriander",
      "Let it rest for 2-3 minutes before serving",
      "Serve hot with naan, roti, or jeera rice",
    ],
    nutritionClassification: {
      protein: "18g per serving",
      carbs: "32g per serving",
      fats: "28g per serving",
      fiber: "4g per serving",
    },
    tipsAndTricks: [
      "Soaking paneer in warm water makes it soft and prevents it from breaking",
      "Use fresh cream for better taste and consistency",
      "Adjust spice levels according to preference",
    ],
    isHighProtein: true,
    timeOfDay: "evening",
    isFeatured: true,
  },
  {
    id: "2",
    name: "Chicken Biryani",
    category: "Non-Veg",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837097/recipe-reveal/recipes-images/chicken-biryani-16-4_ossstp.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837094/recipe-reveal/recipes-images/chicken-birayani-1-1_u44uue.png',
    rating: 4.9,
    reviews: 567,
    prepTime: "40min",
    cookTime: "45min",
    calories: 580,
    protein: 32,
    description:
      "Aromatic and flavorful layered rice dish with marinated chicken, fragrant spices, and caramelized onions. A celebration dish loved across India.",
    ingredients: [
      {
        name: "Chicken",
        quantity: "1kg",
        priceRange: "₹200-280",
        estimatedPrice: 240,
      },
      {
        name: "Basmati Rice",
        quantity: "500g",
        priceRange: "₹80-120",
        estimatedPrice: 100,
      },
      {
        name: "Yogurt",
        quantity: "1 cup",
        priceRange: "₹30-50",
        estimatedPrice: 40,
      },
      {
        name: "Onions",
        quantity: "4 large",
        priceRange: "₹30-50",
        estimatedPrice: 40,
      },
      {
        name: "Whole Spices",
        quantity: "Mix",
        priceRange: "₹30-50",
        estimatedPrice: 40,
      },
      {
        name: "Saffron",
        quantity: "1/4 tsp",
        priceRange: "₹20-40",
        estimatedPrice: 30,
      },
      {
        name: "Ghee",
        quantity: "4 tbsp",
        priceRange: "₹40-60",
        estimatedPrice: 50,
      },
    ],
    preCookingProcess: [
      "Marinate chicken with yogurt, ginger-garlic paste, red chili, turmeric for 30 minutes",
      "Soak basmati rice for 30 minutes and drain",
      "Thinly slice onions and deep fry until golden brown",
      "Soak saffron in warm milk",
    ],
    cookingProcess: [
      "Boil rice with whole spices until 70% cooked. Drain and set aside",
      "In a heavy-bottomed pot, cook marinated chicken with half of fried onions",
      "Layer half of the rice over cooked chicken",
      "Sprinkle remaining fried onions, mint, and saffron milk",
      "Add remaining rice and seal with dough or tight lid",
      "Cook on high heat for 3 minutes, then low heat for 25-30 minutes (dum)",
    ],
    postCookingProcess: [
      "Let it rest for 5 minutes after turning off heat",
      "Gently mix layers while serving",
      "Serve hot with raita and pickle",
    ],
    nutritionClassification: {
      protein: "32g per serving",
      carbs: "68g per serving",
      fats: "18g per serving",
      fiber: "3g per serving",
    },
    tipsAndTricks: [
      "Use good quality basmati rice for best results",
      "Dum cooking is crucial - use low heat and seal properly",
      "Don't skip the fried onions - they add essential flavor",
    ],
    isHighProtein: true,
    timeOfDay: "afternoon",
    isFeatured: true,
  },
  {
    id: "3",
    name: "Moong Dal Chilla",
    category: "Vegan",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837103/recipe-reveal/recipes-images/moong-dal-chilla-16-4_qtcqfk.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837100/recipe-reveal/recipes-images/moong-dal-chilla-1-1_meppiy.png',
    rating: 4.6,
    reviews: 189,
    prepTime: "10min",
    cookTime: "15min",
    calories: 280,
    protein: 14,
    description:
      "Healthy and protein-rich savory pancakes made from moong dal. Perfect for breakfast or evening snack.",
    ingredients: [
      {
        name: "Moong Dal (Yellow)",
        quantity: "1 cup",
        priceRange: "₹100-140",
        estimatedPrice: 120,
      },
      {
        name: "Onions",
        quantity: "1 medium",
        priceRange: "₹8-15",
        estimatedPrice: 10,
      },
      {
        name: "Tomatoes",
        quantity: "1 medium",
        priceRange: "₹8-12",
        estimatedPrice: 10,
      },
      {
        name: "Green Chilies",
        quantity: "2",
        priceRange: "₹5-10",
        estimatedPrice: 7,
      },
      {
        name: "Ginger",
        quantity: "1 inch",
        priceRange: "₹5-10",
        estimatedPrice: 7,
      },
      {
        name: "Coriander Leaves",
        quantity: "2 tbsp",
        priceRange: "₹5-10",
        estimatedPrice: 7,
      },
    ],
    preCookingProcess: [
      "Soak moong dal for 4-6 hours or overnight",
      "Drain and grind to a smooth batter with minimal water",
      "Finely chop onions, tomatoes, green chilies, and ginger",
      "Mix all vegetables into the batter with salt",
    ],
    cookingProcess: [
      "Heat a non-stick pan or tawa over medium heat",
      "Pour a ladleful of batter and spread in circular motion",
      "Drizzle oil or ghee around edges",
      "Cook until golden brown on one side (2-3 minutes)",
      "Flip and cook the other side until crispy",
    ],
    postCookingProcess: [
      "Serve immediately while hot and crispy",
      "Pair with green chutney or tomato ketchup",
      "Can be served with yogurt on the side",
    ],
    nutritionClassification: {
      protein: "14g per serving",
      carbs: "38g per serving",
      fats: "6g per serving",
      fiber: "8g per serving",
    },
    tipsAndTricks: [
      "Batter consistency should be like dosa batter - not too thick",
      "Add vegetables just before making to keep them fresh",
      "Make on medium heat for even cooking",
    ],
    isHighProtein: true,
    timeOfDay: "morning",
    isFeatured: true,
  },
  {
    id: "4",
    name: "Pallak Paneer",
    category: "Other",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837099/recipe-reveal/recipes-images/pallak-paneer-16-4_tqtray.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837099/recipe-reveal/recipes-images/pallak-paneer-1-1_pjf7kh.png',
    rating: 4.7,
    reviews: 298,
    prepTime: "15min",
    cookTime: "25min",
    calories: 350,
    protein: 16,
    description:
      "Creamy spinach curry with soft paneer cubes. A nutritious and delicious North Indian classic.",
    ingredients: [
      {
        name: "Spinach (Palak)",
        quantity: "500g",
        priceRange: "₹20-40",
        estimatedPrice: 30,
      },
      {
        name: "Paneer",
        quantity: "250g",
        priceRange: "₹60-90",
        estimatedPrice: 75,
      },
      {
        name: "Onions",
        quantity: "2 medium",
        priceRange: "₹15-25",
        estimatedPrice: 20,
      },
      {
        name: "Tomatoes",
        quantity: "2 medium",
        priceRange: "₹15-20",
        estimatedPrice: 18,
      },
      {
        name: "Cream",
        quantity: "3 tbsp",
        priceRange: "₹20-30",
        estimatedPrice: 25,
      },
      {
        name: "Garam Masala",
        quantity: "1 tsp",
        priceRange: "₹3-5",
        estimatedPrice: 4,
      },
    ],
    preCookingProcess: [
      "Wash spinach thoroughly and blanch in boiling water for 2 minutes",
      "Immediately transfer to ice water to retain green color",
      "Blend blanched spinach to a smooth puree",
      "Cut paneer into cubes and lightly fry",
    ],
    cookingProcess: [
      "Heat ghee in a pan and add cumin seeds",
      "Sauté chopped onions until golden",
      "Add ginger-garlic paste and cook for 1 minute",
      "Add chopped tomatoes and cook until soft",
      "Add spinach puree and all spices",
      "Simmer for 5-7 minutes",
      "Add paneer cubes and cook for 3 minutes",
      "Finish with cream",
    ],
    postCookingProcess: [
      "Garnish with cream swirl",
      "Serve hot with roti or naan",
      "Pairs well with jeera rice",
    ],
    nutritionClassification: {
      protein: "16g per serving",
      carbs: "22g per serving",
      fats: "24g per serving",
      fiber: "6g per serving",
    },
    tipsAndTricks: [
      "Blanching spinach keeps it bright green",
      "Don't overcook spinach or it will turn dark",
      "Add paneer just before serving to keep it soft",
    ],
    isHighProtein: true,
    timeOfDay: "evening",
    isFeatured: true,
  },
  {
    id: "5",
    name: "Masala Dosa",
    category: "Vegan",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837099/recipe-reveal/recipes-images/masala-dhosa-16-4_xjcmax.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837098/recipe-reveal/recipes-images/masala-dhosa-1-1_zusv8o.png',
    rating: 4.9,
    reviews: 456,
    prepTime: "8 hours (fermentation)",
    cookTime: "20min",
    calories: 320,
    protein: 8,
    description:
      "Crispy rice and lentil crepe filled with spiced potato filling. A South Indian breakfast favorite.",
    ingredients: [
      {
        name: "Dosa Rice",
        quantity: "2 cups",
        priceRange: "₹80-120",
        estimatedPrice: 100,
      },
      {
        name: "Urad Dal",
        quantity: "1/2 cup",
        priceRange: "₹50-80",
        estimatedPrice: 65,
      },
      {
        name: "Potatoes",
        quantity: "4 medium",
        priceRange: "₹20-35",
        estimatedPrice: 28,
      },
      {
        name: "Onions",
        quantity: "2 medium",
        priceRange: "₹15-25",
        estimatedPrice: 20,
      },
      {
        name: "Mustard Seeds",
        quantity: "1 tsp",
        priceRange: "₹3-5",
        estimatedPrice: 4,
      },
      {
        name: "Curry Leaves",
        quantity: "10-12",
        priceRange: "₹5-10",
        estimatedPrice: 7,
      },
    ],
    preCookingProcess: [
      "Soak rice and urad dal separately for 6 hours",
      "Grind separately to smooth batter",
      "Mix and ferment for 8-12 hours",
      "Boil and mash potatoes for filling",
    ],
    cookingProcess: [
      "For filling: temper mustard seeds, curry leaves, add onions",
      "Add mashed potatoes, turmeric, and salt. Mix well",
      "Heat dosa tawa and spread batter thinly",
      "Drizzle oil around edges",
      "When crispy, place potato filling in center",
      "Fold dosa and cook until golden brown",
    ],
    postCookingProcess: [
      "Serve immediately while crispy",
      "Accompany with coconut chutney and sambar",
      "Can be served with tomato chutney",
    ],
    nutritionClassification: {
      protein: "8g per serving",
      carbs: "52g per serving",
      fats: "8g per serving",
      fiber: "5g per serving",
    },
    tipsAndTricks: [
      "Fermentation is key for crispy dosas",
      "Tawa should be hot but not smoking",
      "Use less oil for healthier version",
    ],
    isHighProtein: false,
    timeOfDay: "morning",
    isFeatured: true,
  },
  {
    id: "6",
    name: "Chole Bhature",
    category: "Vegan",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837095/recipe-reveal/recipes-images/chole-bhature-16-4_kyhdob.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837092/recipe-reveal/recipes-images/chole-bhature-1-1_axdvqb.png',
    rating: 4.8,
    reviews: 402,
    prepTime: "8 hours (soaking)",
    cookTime: "50min",
    calories: 520,
    protein: 15,
    description:
      "Spicy chickpea curry served with fluffy deep-fried bread. A popular North Indian breakfast dish.",
    ingredients: [
      {
        name: "Chickpeas",
        quantity: "2 cups",
        priceRange: "₹80-120",
        estimatedPrice: 100,
      },
      {
        name: "All Purpose Flour",
        quantity: "3 cups",
        priceRange: "₹40-60",
        estimatedPrice: 50,
      },
      {
        name: "Yogurt",
        quantity: "1/2 cup",
        priceRange: "₹15-25",
        estimatedPrice: 20,
      },
      {
        name: "Tomatoes",
        quantity: "3 medium",
        priceRange: "₹20-30",
        estimatedPrice: 25,
      },
      {
        name: "Onions",
        quantity: "2 large",
        priceRange: "₹15-25",
        estimatedPrice: 20,
      },
      {
        name: "Chole Masala",
        quantity: "2 tbsp",
        priceRange: "₹10-20",
        estimatedPrice: 15,
      },
    ],
    preCookingProcess: [
      "Soak chickpeas overnight (8 hours)",
      "Pressure cook chickpeas until soft",
      "Knead bhature dough with flour, yogurt, and baking powder. Rest for 2 hours",
      "Prepare onion-tomato base for chole",
    ],
    cookingProcess: [
      "For Chole: Sauté onions until golden, add tomato puree",
      "Add all spices and cook until oil separates",
      "Add boiled chickpeas and simmer for 20 minutes",
      "For Bhature: Roll dough into circles",
      "Deep fry in hot oil until puffed and golden",
    ],
    postCookingProcess: [
      "Serve chole hot, garnished with onions and lemon",
      "Serve bhature immediately after frying",
      "Accompany with pickle and green chutney",
    ],
    nutritionClassification: {
      protein: "15g per serving",
      carbs: "72g per serving",
      fats: "18g per serving",
      fiber: "12g per serving",
    },
    tipsAndTricks: [
      "Adding tea bags while boiling chickpeas gives dark color",
      "Bhature dough should be soft and well-rested",
      "Fry bhature on medium-high heat for best puff",
    ],
    isHighProtein: true,
    timeOfDay: "morning",
    isFeatured: true,
  },
  {
    id: "7",
    name: "Fish Curry (Bengali Style)",
    category: "Non-Veg",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837096/recipe-reveal/recipes-images/fish-curry-16-4_dvlsc7.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837096/recipe-reveal/recipes-images/fish-curry-1-1_pfyet4.png',
    rating: 4.7,
    reviews: 178,
    prepTime: "15min",
    cookTime: "25min",
    calories: 280,
    protein: 28,
    description:
      "Light and flavorful Bengali fish curry cooked in mustard and tomato gravy. Best served with steamed rice.",
    ingredients: [
      {
        name: "Fish (Rohu/Katla)",
        quantity: "500g",
        priceRange: "₹200-300",
        estimatedPrice: 250,
      },
      {
        name: "Mustard Oil",
        quantity: "3 tbsp",
        priceRange: "₹15-25",
        estimatedPrice: 20,
      },
      {
        name: "Tomatoes",
        quantity: "2 medium",
        priceRange: "₹15-20",
        estimatedPrice: 18,
      },
      {
        name: "Mustard Seeds",
        quantity: "2 tsp",
        priceRange: "₹5-8",
        estimatedPrice: 6,
      },
      {
        name: "Turmeric Powder",
        quantity: "1 tsp",
        priceRange: "₹3-5",
        estimatedPrice: 4,
      },
      {
        name: "Green Chilies",
        quantity: "3-4",
        priceRange: "₹5-10",
        estimatedPrice: 7,
      },
    ],
    preCookingProcess: [
      "Wash fish pieces and marinate with turmeric and salt",
      "Grind mustard seeds to a paste",
      "Chop tomatoes and green chilies",
      "Heat mustard oil until smoking, then cool",
    ],
    cookingProcess: [
      "Lightly fry fish pieces in mustard oil until golden. Set aside",
      "In the same oil, temper with nigella seeds",
      "Add chopped tomatoes and cook until soft",
      "Add mustard paste, turmeric, red chili, and salt",
      "Add water and bring to boil",
      "Gently add fried fish pieces",
      "Simmer for 8-10 minutes, add green chilies",
    ],
    postCookingProcess: [
      "Garnish with fresh coriander",
      "Serve hot with steamed rice",
      "Best enjoyed with a squeeze of lemon",
    ],
    nutritionClassification: {
      protein: "28g per serving",
      carbs: "8g per serving",
      fats: "14g per serving",
      fiber: "2g per serving",
    },
    tipsAndTricks: [
      "Mustard oil should be heated until smoking for authentic flavor",
      "Don't overcook fish or it will break",
      "Fresh fish gives best results",
    ],
    isHighProtein: true,
    timeOfDay: "afternoon",
  },
  {
    id: "8",
    name: "Vegetable Pulao",
    category: "Vegan",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837101/recipe-reveal/recipes-images/vegetable-pulao-16-4_zleide.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837103/recipe-reveal/recipes-images/vegetable-pulao-1-1_sxzc9l.png',
    rating: 4.5,
    reviews: 234,
    prepTime: "15min",
    cookTime: "25min",
    calories: 310,
    protein: 7,
    description:
      "Fragrant one-pot rice dish cooked with mixed vegetables and aromatic spices. Perfect for lunch.",
    ingredients: [
      {
        name: "Basmati Rice",
        quantity: "2 cups",
        priceRange: "₹80-120",
        estimatedPrice: 100,
      },
      {
        name: "Mixed Vegetables",
        quantity: "2 cups",
        priceRange: "₹40-60",
        estimatedPrice: 50,
      },
      {
        name: "Onions",
        quantity: "1 large",
        priceRange: "₹8-15",
        estimatedPrice: 12,
      },
      {
        name: "Whole Spices",
        quantity: "Mix",
        priceRange: "₹20-30",
        estimatedPrice: 25,
      },
      {
        name: "Ghee",
        quantity: "2 tbsp",
        priceRange: "₹20-30",
        estimatedPrice: 25,
      },
    ],
    preCookingProcess: [
      "Soak basmati rice for 20 minutes",
      "Chop vegetables (carrots, beans, peas, potatoes)",
      "Thinly slice onions",
      "Prepare whole spices mix",
    ],
    cookingProcess: [
      "Heat ghee in a pot and add whole spices",
      "Add sliced onions and sauté until golden",
      "Add all vegetables and sauté for 3-4 minutes",
      "Add drained rice and gently mix",
      "Add water (1:2 rice to water ratio), salt",
      "Bring to boil, then cover and simmer for 15 minutes",
      "Turn off heat and let it rest for 5 minutes",
    ],
    postCookingProcess: [
      "Fluff with fork gently",
      "Garnish with fried onions and coriander",
      "Serve with raita or curry",
    ],
    nutritionClassification: {
      protein: "7g per serving",
      carbs: "58g per serving",
      fats: "8g per serving",
      fiber: "4g per serving",
    },
    tipsAndTricks: [
      "Don't overcook rice - it should be separate and fluffy",
      "Use fresh vegetables for best taste",
      "Adding lemon juice enhances flavor",
    ],
    isHighProtein: false,
    timeOfDay: "afternoon",
  },
  {
    id: "9",
    name: "Egg Curry",
    category: "Non-Veg",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837094/recipe-reveal/recipes-images/egg-curry-16-4_oyvm35.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837096/recipe-reveal/recipes-images/egg-curry-1-1_utzdgw.png',
    rating: 4.6,
    reviews: 312,
    prepTime: "10min",
    cookTime: "20min",
    calories: 290,
    protein: 14,
    description:
      "Simple and delicious curry made with boiled eggs in spiced onion-tomato gravy. Quick weeknight dinner option.",
    ingredients: [
      { name: "Eggs", quantity: "6", priceRange: "₹30-45", estimatedPrice: 38 },
      {
        name: "Onions",
        quantity: "2 large",
        priceRange: "₹15-25",
        estimatedPrice: 20,
      },
      {
        name: "Tomatoes",
        quantity: "3 medium",
        priceRange: "₹20-30",
        estimatedPrice: 25,
      },
      {
        name: "Coconut Milk",
        quantity: "1/2 cup",
        priceRange: "₹25-40",
        estimatedPrice: 32,
      },
      {
        name: "Curry Leaves",
        quantity: "10",
        priceRange: "₹5-10",
        estimatedPrice: 7,
      },
    ],
    preCookingProcess: [
      "Boil eggs until hard-boiled (10 minutes)",
      "Peel and make shallow cuts on eggs",
      "Finely chop onions and tomatoes",
      "Prepare ginger-garlic paste",
    ],
    cookingProcess: [
      "Heat oil and add curry leaves, mustard seeds",
      "Sauté chopped onions until golden brown",
      "Add ginger-garlic paste and cook for 1 minute",
      "Add tomatoes and cook until mushy",
      "Add all spices and cook until oil separates",
      "Add coconut milk and water, bring to boil",
      "Add boiled eggs and simmer for 5 minutes",
    ],
    postCookingProcess: [
      "Garnish with coriander leaves",
      "Serve hot with rice or roti",
      "Can be stored in refrigerator for 2 days",
    ],
    nutritionClassification: {
      protein: "14g per serving",
      carbs: "18g per serving",
      fats: "16g per serving",
      fiber: "3g per serving",
    },
    tipsAndTricks: [
      "Making cuts on eggs helps absorb flavors",
      "Can add potatoes for a more filling meal",
      "Adjust coconut milk for desired creaminess",
    ],
    isHighProtein: true,
    timeOfDay: "night",
  },
  {
    id: "10",
    name: "Rajma Masala",
    category: "Vegan",
    image: "https://res.cloudinary.com/rf-automation-test/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1761837102/recipe-reveal/recipes-images/rajma-masala-16-4_maqvwp.png",
    prevImage: 'https://res.cloudinary.com/rf-automation-test/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1761837103/recipe-reveal/recipes-images/rajma-masala-1-1_wu882d.png',
    rating: 4.7,
    reviews: 289,
    prepTime: "8 hours (soaking)",
    cookTime: "40min",
    calories: 340,
    protein: 16,
    description:
      "Hearty kidney bean curry in thick tomato-onion gravy. A protein-rich North Indian comfort food.",
    ingredients: [
      {
        name: "Rajma (Kidney Beans)",
        quantity: "2 cups",
        priceRange: "₹100-150",
        estimatedPrice: 125,
      },
      {
        name: "Onions",
        quantity: "2 large",
        priceRange: "₹15-25",
        estimatedPrice: 20,
      },
      {
        name: "Tomatoes",
        quantity: "4 medium",
        priceRange: "₹25-35",
        estimatedPrice: 30,
      },
      {
        name: "Ginger-Garlic Paste",
        quantity: "2 tbsp",
        priceRange: "₹10-15",
        estimatedPrice: 12,
      },
      {
        name: "Rajma Masala",
        quantity: "1 tbsp",
        priceRange: "₹8-15",
        estimatedPrice: 12,
      },
    ],
    preCookingProcess: [
      "Soak rajma overnight (8 hours)",
      "Pressure cook rajma until very soft (5-6 whistles)",
      "Prepare onion-tomato paste by blending",
      "Keep rajma water aside for gravy",
    ],
    cookingProcess: [
      "Heat oil and add cumin seeds",
      "Add finely chopped onions and cook until golden",
      "Add ginger-garlic paste and cook for 1 minute",
      "Add tomato puree and cook until oil separates",
      "Add all spices and cook for 2 minutes",
      "Add boiled rajma with cooking water",
      "Simmer for 15-20 minutes for flavors to blend",
      "Mash some beans for thickness",
    ],
    postCookingProcess: [
      "Garnish with ginger julienne and coriander",
      "Serve hot with steamed rice",
      "Tastes better the next day",
    ],
    nutritionClassification: {
      protein: "16g per serving",
      carbs: "48g per serving",
      fats: "6g per serving",
      fiber: "14g per serving",
    },
    tipsAndTricks: [
      "Rajma must be very soft for best curry",
      "Slow cooking enhances flavors",
      "Add a pinch of sugar to balance acidity",
    ],
    isHighProtein: true,
    timeOfDay: "afternoon",
  },
];

const newRecipe = [
  {
    id: "11",
    name: "Butter Chicken Makhani",
    category: "non-veg",
    image: "butter chicken makhani",
    prevImage: '',
    prevImage: "",
    prevImage: '',
    rating: 4.7,
    reviews: 289,
    prepTime: "20min",
    cookTime: "40min",
    calories: 340,
    protein: 180,
    description:
      "A popular North Indian dish rich ,creamy and mild spicy curry made with marinated chicken cooked in a tandoor and simmered in a velvety tomato sauce with butter and cream. Can be served with Roti ,naan or rice",
    ingredients: [
      {
        name: "Chicken(boneless)",
        quantity: "500g",
        priceRange: "100-150",
        estimatedPrice: 130,
      },
      {
        name: "tomato puree",
        quantity: "1 cup",
        priceRange: "20-40",
        estimatedPrice: 20,
      },
      {
        name: "cooking oil",
        quantity: "1 tbsp",
        priceRange: "30-60",
        estimatedPrice: 40,
      },
      {
        name: "Garam Masala",
        quantity: "1 tbsp",
        priceRange: "10-20",
        estimatedPrice: 15,
      },
      {
        name: "Yogurt",
        quantity: "1 cup",
        priceRange: "30-50",
        estimatedPrice: 120,
      },
      {
        name: " grated ginger garlic",
        quantity: "1 tbsp",
        priceRange: "10-20",
        estimatedPrice: 100,
      },
      {
        name: "large sliced onion",
        quantity: "1",
        priceRange: "20-30",
        estimatedPrice: 20,
      },
      {
        name: "unsalted butter",
        quantity: "4 tbsp",
        priceRange: "30-50",
        estimatedPrice: 30,
      },
      {
        name: "cashews",
        quantity: "1/4 tbsp",
        priceRange: "40-60",
        estimatedPrice: 50,
      },
      {
        name: "lemon juice",
        quantity: "1 tbsp",
        priceRange: "10-40",
        estimatedPrice: 20,
      },
      {
        name: "heavy cream",
        quantity: "1/2 tbsp",
        priceRange: "40-50",
        estimatedPrice: 40,
      },
      {
        name: "honey",
        quantity: "1 tbsp",
        priceRange: "40-50",
        estimatedPrice: 40,
      },
      {
        name: "kasuri meethi(fenugreek leaves)",
        quantity: "1 tbsp",
        priceRange: "20-40",
        estimatedPrice: 30,
      },
      {
        name: "water",
        quantity: "1 cup",
        priceRange: "10-20",
        estimatedPrice: 12,
      },
    ],
    preCookingProcess: [
      "Marinate the chicken.",
      "Combine all the marinade ingredients in a large bowl.",
      "Add the chicken cubes and mix until every piece is evenly coated.",
      "Cover and refrigerate for at least one hour for the best flavour.",
    ],
    cookingProcess: {
      "Prepare the sauce base": [
        "Heat 2 tbsp of butter and 1 tbsp of oil in a large saucepan over medium heat.",
        "Add the cardamom, cinnamon, and cloves and sauté for 30 seconds until fragrant.",
        "Stir in the sliced onions and cook for 7–8 minutes until they become soft and lightly golden.",
        "Add the cashews, ginger, and garlic. Continue to cook for another minute.",
        "Pour in the tomato purée and add the Kashmiri red chili powder, cumin, coriander, and garam masala. Cook the mixture for 15–20 minutes, stirring occasionally, until the tomatoes are soft and mushy and the butter begins to separate from the sauce.",
      ],
      "Blend the sauce": [
        "Remove and discard the whole spices (cinnamon stick, cardamom, cloves) for a smoother texture.",
        "Allow the mixture to cool slightly before transferring it to a blender.",
        "Add 1 cup of water and blend until a very smooth, lump-free paste forms.",
      ],
      "Cook the chicken": [
        "Heat melt 1 tbsp of butter.",
        "Place the marinated chicken pieces in a single layer, making sure not to overcrowd the pan.",
        "Sear the chicken on all sides over medium-high heat until it is lightly browned and just cooked through. This should take 5–7 minutes.",
        "Set the cooked chicken aside on a plate.",
      ],
      "Combine and finish the curry": [
        "Bring the strained tomato sauce to a gentle simmer over medium-low heat.",
        "Stir in the cooked chicken and allow it to simmer for 5–7 minutes, allowing the chicken to absorb the sauce's flavor.",
        "Add the remaining butter, the kasuri methi, honey, and heavy cream. Stir gently to combine.",
        "Simmer for another 2 minutes, but do not boil after adding the cream.",
      ],
    },
    postCookingProcess: [
      "[3:45 pm, 30/10/2025] +91 72610 30200: Taste and adjust the salt and sugar if necessary",
      "Serve hot with fluffy basmati rice, naan, or paratha.",
      "Add a side of kachumber salad (Indian salad) for a fresh contrast.",
    ],
    nutritionClassification: {
      protein: "16g per serving",
      carbs: "48g per serving",
      fats: "6g per serving",
      fiber: "14g per serving",
    },
    tipsAndTricks: [
      "Rajma must be very soft for best curry",
      "Slow cooking enhances flavors",
      "Add a pinch of sugar to balance acidity",
    ],
    isHighProtein: true,
    timeOfDay: "afternoon",
  },
];

export const getRecipeById = (id) => {
  return recipes.find((recipe) => recipe.id === id);
};

export const getFeaturedRecipes = () => {
  return recipes.filter((recipe) => recipe.isFeatured).slice(0, 6);
};

export const getHighProteinRecipeByTime = () => {
  const hour = new Date().getHours();
  // timeOfDay == 'morning' | 'afternoon' | 'evening' | 'night'
  let timeOfDay;

  if (hour >= 5 && hour < 12) {
    timeOfDay = "morning";
  } else if (hour >= 12 && hour < 17) {
    timeOfDay = "afternoon";
  } else if (hour >= 17 && hour < 21) {
    timeOfDay = "evening";
  } else {
    timeOfDay = "night";
  }

  const timeBasedRecipes = recipes.filter(
    (recipe) => recipe.isHighProtein && recipe.timeOfDay === timeOfDay
  );
  return timeBasedRecipes[0] || recipes.filter((r) => r.isHighProtein)[0];
};

// category ==> 'Vegan' | 'Non-Veg' | 'Other' | 'All'
export const getRecipesByCategory = (category) => {
  if (category === "All") return recipes;
  return recipes.filter((recipe) => recipe.category === category);
};
